apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lol-ceaee-certificate
  namespace: lol-ceaee
spec:
  secretName: lol-ceaee-secret-tls
  commonName: thanak81-lol.assessify.org
  dnsNames:
  - thanak81-lol.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
